/**
 * GOFAI Domain Nouns — Batch 3: World Music, Texture, Arrangement, Production
 *
 * Continuation with diverse musical traditions and production terminology.
 *
 * @module gofai/canon/domain-nouns-batch3
 */

import {
  createLexemeId,
} from './types';
import type { DomainNoun } from './domain-nouns';

// =============================================================================
// World Music Scales and Modes
// =============================================================================

const WORLD_MUSIC_SCALES: readonly DomainNoun[] = [
  {
    id: createLexemeId('noun', 'maqam'),
    term: 'maqam',
    variants: ['maqamat', 'makam', 'Arabic mode'],
    category: 'world_scale',
    definition: 'Arabic/Turkish modal system with microtonal intervals',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use maqam scale', 'apply maqam Rast'],
    tradition: 'Arabic/Turkish',
  },
  {
    id: createLexemeId('noun', 'raga'),
    term: 'raga',
    variants: ['raag', 'Indian mode'],
    category: 'world_scale',
    definition: 'Melodic framework in Indian classical music',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use raga Bhairav', 'follow raga rules'],
    tradition: 'Indian classical',
  },
  {
    id: createLexemeId('noun', 'pelog'),
    term: 'pelog',
    variants: ['pélog scale'],
    category: 'world_scale',
    definition: 'Seven-tone gamelan scale with non-equal intervals',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use pelog scale'],
    tradition: 'Indonesian',
  },
  {
    id: createLexemeId('noun', 'slendro'),
    term: 'slendro',
    variants: ['sléndro scale'],
    category: 'world_scale',
    definition: 'Five-tone gamelan scale with near-equal intervals',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use slendro tuning'],
    tradition: 'Indonesian',
  },
  {
    id: createLexemeId('noun', 'in-sen'),
    term: 'in-sen',
    variants: ['Japanese pentatonic', 'in scale'],
    category: 'world_scale',
    definition: 'Japanese pentatonic scale',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use in-sen scale'],
    tradition: 'Japanese',
  },
  {
    id: createLexemeId('noun', 'hirajoshi'),
    term: 'hirajoshi',
    variants: ['hira-joshi'],
    category: 'world_scale',
    definition: 'Japanese pentatonic scale with minor second',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use hirajoshi scale'],
    tradition: 'Japanese',
  },
  {
    id: createLexemeId('noun', 'yo-scale'),
    term: 'yo scale',
    variants: ['Japanese pentatonic'],
    category: 'world_scale',
    definition: 'Japanese pentatonic without half steps',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use yo scale'],
    tradition: 'Japanese',
  },
  {
    id: createLexemeId('noun', 'phrygian-dominant'),
    term: 'Phrygian dominant',
    variants: ['freygish', 'Spanish Phrygian', 'Jewish scale'],
    category: 'world_scale',
    definition: 'Phrygian mode with major third',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use Phrygian dominant'],
    tradition: 'Middle Eastern/Klezmer',
  },
  {
    id: createLexemeId('noun', 'double-harmonic'),
    term: 'double harmonic',
    variants: ['Byzantine scale', 'Arabic scale', 'gypsy major'],
    category: 'world_scale',
    definition: 'Scale with two augmented seconds',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use double harmonic scale'],
    tradition: 'Middle Eastern/Byzantine',
  },
  {
    id: createLexemeId('noun', 'hungarian-minor'),
    term: 'Hungarian minor',
    variants: ['Hungarian gypsy'],
    category: 'world_scale',
    definition: 'Minor scale with raised fourth and seventh',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use Hungarian minor'],
    tradition: 'Hungarian/Romani',
  },
  {
    id: createLexemeId('noun', 'flamenco-mode'),
    term: 'flamenco mode',
    variants: ['Phrygian Spanish'],
    category: 'world_scale',
    definition: 'Phrygian with characteristic cadence patterns',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use flamenco mode'],
    tradition: 'Spanish flamenco',
  },
  {
    id: createLexemeId('noun', 'klezmer-scale'),
    term: 'klezmer scale',
    variants: ['Ahava Rabboh', 'freygish'],
    category: 'world_scale',
    definition: 'Phrygian dominant used in klezmer music',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use klezmer scale'],
    tradition: 'Ashkenazi Jewish',
  },
  {
    id: createLexemeId('noun', 'kumoi'),
    term: 'kumoi',
    variants: ['kumoijoshi'],
    category: 'world_scale',
    definition: 'Japanese pentatonic scale',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use kumoi scale'],
    tradition: 'Japanese',
  },
  {
    id: createLexemeId('noun', 'iwato'),
    term: 'iwato',
    variants: ['iwato scale'],
    category: 'world_scale',
    definition: 'Japanese pentatonic with minor seconds',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use iwato scale'],
    tradition: 'Japanese',
  },
  {
    id: createLexemeId('noun', 'chinese-pentatonic'),
    term: 'Chinese pentatonic',
    variants: ['gong mode', 'anhemitonic pentatonic'],
    category: 'world_scale',
    definition: 'Pentatonic without half steps',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use Chinese pentatonic'],
    tradition: 'Chinese',
  },
  {
    id: createLexemeId('noun', 'bhairav'),
    term: 'Bhairav',
    variants: ['raga Bhairav'],
    category: 'world_scale',
    definition: 'North Indian raga with characteristic intervals',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['perform in Bhairav'],
    tradition: 'Indian classical',
  },
  {
    id: createLexemeId('noun', 'carnatic-raga'),
    term: 'Carnatic raga',
    variants: ['South Indian raga'],
    category: 'world_scale',
    definition: 'South Indian classical melodic framework',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use Carnatic raga'],
    tradition: 'South Indian classical',
  },

  // Texture nouns
  {
    id: createLexemeId('noun', 'texture'),
    term: 'texture',
    variants: ['musical texture', 'fabric'],
    category: 'texture',
    definition: 'Density and relationship of simultaneous musical lines',
    semantics: { type: 'quality', qualityDimension: 'arrangement' },
    examples: ['thin the texture', 'thicken the texture'],
  },
  {
    id: createLexemeId('noun', 'monophony'),
    term: 'monophony',
    variants: ['monophonic texture', 'single line'],
    category: 'texture',
    definition: 'Single melodic line without accompaniment',
    semantics: { type: 'property', propertyOf: 'texture' },
    examples: ['reduce to monophony', 'use monophonic texture'],
  },
  {
    id: createLexemeId('noun', 'homophony'),
    term: 'homophony',
    variants: ['homophonic texture', 'melody with accompaniment'],
    category: 'texture',
    definition: 'Melody with chordal accompaniment',
    semantics: { type: 'property', propertyOf: 'texture' },
    examples: ['use homophonic texture'],
  },
  {
    id: createLexemeId('noun', 'polyphony'),
    term: 'polyphony',
    variants: ['polyphonic texture', 'counterpoint'],
    category: 'texture',
    definition: 'Multiple independent melodic lines',
    semantics: { type: 'property', propertyOf: 'texture' },
    examples: ['add polyphonic lines', 'create polyphony'],
  },
  {
    id: createLexemeId('noun', 'counterpoint'),
    term: 'counterpoint',
    variants: ['contrapuntal texture'],
    category: 'texture',
    definition: 'Art of combining independent melodic lines',
    semantics: { type: 'quality', qualityDimension: 'arrangement' },
    examples: ['add counterpoint', 'write contrapuntal lines'],
  },
  {
    id: createLexemeId('noun', 'heterophony'),
    term: 'heterophony',
    variants: ['heterophonic texture'],
    category: 'texture',
    definition: 'Simultaneous variations of same melody',
    semantics: { type: 'property', propertyOf: 'texture' },
    examples: ['use heterophonic texture'],
    tradition: 'Various non-Western',
  },
  {
    id: createLexemeId('noun', 'hocket'),
    term: 'hocket',
    variants: ['hocketing'],
    category: 'texture',
    definition: 'Melody split between voices with rapid alternation',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add hocket effect', 'use hocketing'],
    tradition: 'Medieval',
  },
  {
    id: createLexemeId('noun', 'density'),
    term: 'density',
    variants: ['note density', 'event density'],
    category: 'texture',
    definition: 'Number of events per unit time',
    semantics: { type: 'quality', qualityDimension: 'rhythmic' },
    examples: ['reduce density', 'increase note density'],
  },
  {
    id: createLexemeId('noun', 'space'),
    term: 'space',
    variants: ['breathing room', 'air'],
    category: 'texture',
    definition: 'Absence of activity, silence between events',
    semantics: { type: 'quality', qualityDimension: 'arrangement' },
    examples: ['add more space', 'give it breathing room'],
  },
  {
    id: createLexemeId('noun', 'layering'),
    term: 'layering',
    variants: ['layers', 'stacking'],
    category: 'texture',
    definition: 'Combining multiple parts or timbres',
    semantics: { type: 'process', processType: 'arrangement' },
    examples: ['add layering', 'reduce layers'],
  },
  {
    id: createLexemeId('noun', 'doubling'),
    term: 'doubling',
    variants: ['unison doubling', 'octave doubling'],
    category: 'texture',
    definition: 'Playing same material on multiple instruments',
    semantics: { type: 'process', processType: 'arrangement' },
    examples: ['add doubling', 'double the melody'],
  },

  // Arrangement nouns
  {
    id: createLexemeId('noun', 'arrangement'),
    term: 'arrangement',
    variants: ['orchestration', 'instrumentation'],
    category: 'arrangement',
    definition: 'Distribution of musical material across instruments',
    semantics: { type: 'property', propertyOf: 'structure' },
    examples: ['change the arrangement', 'simplify arrangement'],
  },
  {
    id: createLexemeId('noun', 'orchestration'),
    term: 'orchestration',
    variants: ['instrumentation', 'voicing'],
    category: 'arrangement',
    definition: 'Art of assigning parts to specific instruments',
    semantics: { type: 'process', processType: 'arrangement' },
    examples: ['improve orchestration', 're-orchestrate'],
  },
  {
    id: createLexemeId('noun', 'instrumentation'),
    term: 'instrumentation',
    variants: ['instrument choice', 'timbral palette'],
    category: 'arrangement',
    definition: 'Selection and combination of instruments',
    semantics: { type: 'property', propertyOf: 'arrangement' },
    examples: ['vary instrumentation', 'change instruments'],
  },
  {
    id: createLexemeId('noun', 'lead'),
    term: 'lead',
    variants: ['lead line', 'melody', 'top line'],
    category: 'role',
    definition: 'Primary melodic voice',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['brighten the lead', 'isolate the lead'],
  },
  {
    id: createLexemeId('noun', 'bass'),
    term: 'bass',
    variants: ['bassline', 'bass part', 'low end'],
    category: 'role',
    definition: 'Lowest voice providing harmonic foundation',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['strengthen the bass', 'simplify bassline'],
  },
  {
    id: createLexemeId('noun', 'pad'),
    term: 'pad',
    variants: ['pad sound', 'sustained harmony'],
    category: 'role',
    definition: 'Sustained harmonic texture',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['add a pad', 'thicken the pad'],
  },
  {
    id: createLexemeId('noun', 'accompaniment'),
    term: 'accompaniment',
    variants: ['backing', 'comping'],
    category: 'role',
    definition: 'Supporting harmonic/rhythmic material',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['simplify accompaniment', 'add accompaniment'],
  },
  {
    id: createLexemeId('noun', 'countermelody'),
    term: 'countermelody',
    variants: ['counter-melody', 'secondary melody'],
    category: 'role',
    definition: 'Secondary melodic line contrasting with main melody',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add countermelody', 'weave in countermelody'],
  },
  {
    id: createLexemeId('noun', 'bass-drum'),
    term: 'kick',
    variants: ['bass drum', 'kick drum', 'BD'],
    category: 'layer',
    definition: 'Low-frequency drum providing pulse',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['punch up the kick', 'emphasize kick'],
  },
  {
    id: createLexemeId('noun', 'snare'),
    term: 'snare',
    variants: ['snare drum', 'SD'],
    category: 'layer',
    definition: 'Mid-frequency drum typically on backbeat',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['tighten the snare', 'ghost the snare'],
  },
  {
    id: createLexemeId('noun', 'hi-hat'),
    term: 'hi-hat',
    variants: ['hats', 'hihat', 'HH'],
    category: 'layer',
    definition: 'Paired cymbals providing rhythmic subdivision',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['open the hi-hats', 'vary hi-hat pattern'],
  },
  {
    id: createLexemeId('noun', 'cymbal'),
    term: 'cymbal',
    variants: ['crash', 'ride', 'splash'],
    category: 'layer',
    definition: 'Metallic percussion for accents and rhythm',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['add cymbal crash', 'use ride cymbal'],
  },
  {
    id: createLexemeId('noun', 'percussion'),
    term: 'percussion',
    variants: ['perc', 'drums'],
    category: 'layer',
    definition: 'Rhythmic instruments',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['add percussion', 'layer percussion'],
  },
  {
    id: createLexemeId('noun', 'string-section'),
    term: 'strings',
    variants: ['string section', 'orchestral strings'],
    category: 'layer',
    definition: 'Violin, viola, cello, bass ensemble',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['add strings', 'swell the strings'],
  },
  {
    id: createLexemeId('noun', 'brass-section'),
    term: 'brass',
    variants: ['brass section', 'horns'],
    category: 'layer',
    definition: 'Trumpet, trombone, tuba ensemble',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['add brass', 'punch up brass'],
  },
  {
    id: createLexemeId('noun', 'woodwinds'),
    term: 'woodwinds',
    variants: ['winds', 'woodwind section'],
    category: 'layer',
    definition: 'Flute, clarinet, oboe, bassoon ensemble',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['add woodwinds', 'feature woodwinds'],
  },
  {
    id: createLexemeId('noun', 'synth'),
    term: 'synth',
    variants: ['synthesizer', 'synth pad', 'synth lead'],
    category: 'layer',
    definition: 'Electronic synthesized sounds',
    semantics: { type: 'entity_ref', entityType: 'layer' },
    examples: ['add synth layer', 'brighten the synth'],
  },

  // Production nouns
  {
    id: createLexemeId('noun', 'reverb'),
    term: 'reverb',
    variants: ['reverberation', 'room sound'],
    category: 'production',
    definition: 'Spatial effect simulating acoustic reflections',
    semantics: { type: 'entity_ref', entityType: 'effect' },
    examples: ['add reverb', 'reduce reverb'],
  },
  {
    id: createLexemeId('noun', 'delay'),
    term: 'delay',
    variants: ['echo', 'delay effect'],
    category: 'production',
    definition: 'Time-based repetition effect',
    semantics: { type: 'entity_ref', entityType: 'effect' },
    examples: ['add delay', 'sync delay to tempo'],
  },
  {
    id: createLexemeId('noun', 'compression'),
    term: 'compression',
    variants: ['compressor', 'dynamic compression'],
    category: 'production',
    definition: 'Dynamic range reduction',
    semantics: { type: 'process', processType: 'production' },
    examples: ['add compression', 'tighten with compression'],
  },
  {
    id: createLexemeId('noun', 'eq'),
    term: 'EQ',
    variants: ['equalization', 'equalizer'],
    category: 'production',
    definition: 'Frequency balance adjustment',
    semantics: { type: 'process', processType: 'production' },
    examples: ['adjust EQ', 'boost mids'],
  },
  {
    id: createLexemeId('noun', 'saturation'),
    term: 'saturation',
    variants: ['harmonic saturation', 'tape saturation'],
    category: 'production',
    definition: 'Harmonic distortion adding warmth',
    semantics: { type: 'process', processType: 'production' },
    examples: ['add saturation', 'warm with saturation'],
  },
  {
    id: createLexemeId('noun', 'distortion'),
    term: 'distortion',
    variants: ['overdrive', 'fuzz'],
    category: 'production',
    definition: 'Aggressive harmonic distortion',
    semantics: { type: 'entity_ref', entityType: 'effect' },
    examples: ['add distortion', 'drive the signal'],
  },
  {
    id: createLexemeId('noun', 'chorus'),
    term: 'chorus effect',
    variants: ['chorus', 'chorusing'],
    category: 'production',
    definition: 'Pitch modulation creating thickness',
    semantics: { type: 'entity_ref', entityType: 'effect' },
    examples: ['add chorus', 'widen with chorus'],
  },
  {
    id: createLexemeId('noun', 'flanger'),
    term: 'flanger',
    variants: ['flanging', 'jet effect'],
    category: 'production',
    definition: 'Comb filtering modulation effect',
    semantics: { type: 'entity_ref', entityType: 'effect' },
    examples: ['add flanger', 'apply flanging'],
  },
  {
    id: createLexemeId('noun', 'phaser'),
    term: 'phaser',
    variants: ['phase shifter'],
    category: 'production',
    definition: 'All-pass filter modulation effect',
    semantics: { type: 'entity_ref', entityType: 'effect' },
    examples: ['add phaser', 'use phase effect'],
  },
  {
    id: createLexemeId('noun', 'filter'),
    term: 'filter',
    variants: ['low-pass', 'high-pass', 'band-pass'],
    category: 'production',
    definition: 'Frequency selective attenuation',
    semantics: { type: 'process', processType: 'production' },
    examples: ['apply filter', 'automate filter sweep'],
  },
  {
    id: createLexemeId('noun', 'sidechain'),
    term: 'sidechain',
    variants: ['sidechaining', 'ducking'],
    category: 'production',
    definition: 'Effect triggered by external signal',
    semantics: { type: 'process', processType: 'production' },
    examples: ['add sidechain compression', 'duck under kick'],
  },
  {
    id: createLexemeId('noun', 'automation'),
    term: 'automation',
    variants: ['parameter automation'],
    category: 'production',
    definition: 'Time-varying parameter changes',
    semantics: { type: 'process', processType: 'production' },
    examples: ['add automation', 'automate the filter'],
  },
  {
    id: createLexemeId('noun', 'stereo-width'),
    term: 'stereo width',
    variants: ['width', 'spread'],
    category: 'production',
    definition: 'Perceived spatial spread',
    semantics: { type: 'quality', qualityDimension: 'spatial' },
    examples: ['increase stereo width', 'narrow the width'],
  },
  {
    id: createLexemeId('noun', 'panning'),
    term: 'panning',
    variants: ['pan', 'stereo position'],
    category: 'production',
    definition: 'Left-right placement in stereo field',
    semantics: { type: 'property', propertyOf: 'spatial' },
    examples: ['pan to the right', 'center the panning'],
  },
  {
    id: createLexemeId('noun', 'transient'),
    term: 'transient',
    variants: ['attack', 'initial transient'],
    category: 'production',
    definition: 'Initial high-energy portion of sound',
    semantics: { type: 'property', propertyOf: 'timbre' },
    examples: ['enhance transients', 'tame the transients'],
  },
  {
    id: createLexemeId('noun', 'envelope'),
    term: 'envelope',
    variants: ['ADSR', 'amplitude envelope'],
    category: 'production',
    definition: 'Time-varying amplitude or parameter shape',
    semantics: { type: 'property', propertyOf: 'timbre' },
    examples: ['adjust envelope', 'lengthen the release'],
  },
  {
    id: createLexemeId('noun', 'attack'),
    term: 'attack',
    variants: ['attack time'],
    category: 'production',
    definition: 'Initial rise time of sound',
    semantics: { type: 'property', propertyOf: 'timbre' },
    examples: ['shorten attack', 'slow the attack'],
  },
  {
    id: createLexemeId('noun', 'release'),
    term: 'release',
    variants: ['release time', 'decay'],
    category: 'production',
    definition: 'Time for sound to fade after note off',
    semantics: { type: 'property', propertyOf: 'timbre' },
    examples: ['lengthen release', 'quick release'],
  },
  {
    id: createLexemeId('noun', 'sustain'),
    term: 'sustain',
    variants: ['sustain level'],
    category: 'production',
    definition: 'Held level after attack before release',
    semantics: { type: 'property', propertyOf: 'timbre' },
    examples: ['increase sustain', 'reduce sustain'],
  },
];

// =============================================================================
// Exports
// =============================================================================

export const DOMAIN_NOUNS_BATCH_3 = WORLD_MUSIC_SCALES;
