/**
 * GOFAI Domain Nouns — Batch 2: Harmony, Melody, Voice Leading, Scales
 *
 * Continuation of the canonical musical terminology inventory.
 *
 * @module gofai/canon/domain-nouns-batch2
 */

import {
  createLexemeId,
} from './types';
import type { DomainNoun } from './domain-nouns';

// =============================================================================
// Harmony Nouns (continued)
// =============================================================================

const HARMONY_NOUNS_CONTINUED: readonly DomainNoun[] = [
  {
    id: createLexemeId('noun', 'augmented-sixth'),
    term: 'augmented sixth',
    variants: ['aug 6', 'Italian sixth', 'French sixth', 'German sixth'],
    category: 'harmony',
    definition: 'Pre-dominant chord with augmented sixth interval above bass',
    semantics: { type: 'entity_ref', entityType: 'chord' },
    examples: ['add augmented sixth chord', 'resolve the augmented sixth'],
    tradition: 'Western classical',
  },
  {
    id: createLexemeId('noun', 'neapolitan'),
    term: 'Neapolitan',
    variants: ['Neapolitan sixth', 'bII', 'flat-II'],
    category: 'harmony',
    definition: 'Major chord built on lowered second scale degree',
    semantics: { type: 'entity_ref', entityType: 'chord' },
    examples: ['use Neapolitan chord', 'resolve from Neapolitan'],
    tradition: 'Western classical',
  },
  {
    id: createLexemeId('noun', 'diminished-seventh'),
    term: 'diminished seventh',
    variants: ['dim7', 'fully diminished'],
    category: 'harmony',
    definition: 'Chord with three minor thirds and diminished seventh',
    semantics: { type: 'entity_ref', entityType: 'chord' },
    examples: ['add diminished seventh', 'use as passing chord'],
  },
  {
    id: createLexemeId('noun', 'half-diminished'),
    term: 'half-diminished',
    variants: ['half-dim', 'minor seven flat five', 'm7b5'],
    category: 'harmony',
    definition: 'Minor seventh chord with diminished fifth',
    semantics: { type: 'entity_ref', entityType: 'chord' },
    examples: ['use half-diminished chord'],
    tradition: 'Jazz',
  },
  {
    id: createLexemeId('noun', 'tritone-substitution'),
    term: 'tritone substitution',
    variants: ['tritone sub', 'flat-five sub'],
    category: 'harmony',
    definition: 'Dominant chord substituted a tritone away',
    semantics: { type: 'process', processType: 'harmonic' },
    examples: ['apply tritone substitution', 'use tritone sub on V7'],
    tradition: 'Jazz',
  },
  {
    id: createLexemeId('noun', 'ii-V-I'),
    term: 'ii-V-I',
    variants: ['two-five-one', 'turnaround', 'jazz cadence'],
    category: 'harmony',
    definition: 'Common jazz progression: ii7 - V7 - Imaj7',
    semantics: { type: 'pattern', patternType: 'harmonic' },
    examples: ['use ii-V-I progression', 'reharmonize the ii-V'],
    tradition: 'Jazz',
  },
  {
    id: createLexemeId('noun', 'altered-dominant'),
    term: 'altered dominant',
    variants: ['alt dom', '7alt', 'superlocrian'],
    category: 'harmony',
    definition: 'Dominant chord with altered fifths and ninths',
    semantics: { type: 'entity_ref', entityType: 'chord' },
    examples: ['use altered dominant', 'resolve the altered chord'],
    tradition: 'Jazz',
  },
  {
    id: createLexemeId('noun', 'lydian-dominant'),
    term: 'Lydian dominant',
    variants: ['acoustic scale chord', 'mixolydian sharp 4'],
    category: 'harmony',
    definition: 'Dominant seventh with raised fourth',
    semantics: { type: 'entity_ref', entityType: 'chord' },
    examples: ['use Lydian dominant sound'],
    tradition: 'Jazz',
  },
  {
    id: createLexemeId('noun', 'slash-chord'),
    term: 'slash chord',
    variants: ['polychord', 'hybrid chord'],
    category: 'harmony',
    definition: 'Chord with specified bass note (e.g., C/E)',
    semantics: { type: 'entity_ref', entityType: 'chord' },
    examples: ['use slash chord notation', 'voice as slash chord'],
  },
  {
    id: createLexemeId('noun', 'power-chord'),
    term: 'power chord',
    variants: ['fifth chord', 'open fifth'],
    category: 'harmony',
    definition: 'Two-note chord of root and fifth, no third',
    semantics: { type: 'entity_ref', entityType: 'chord' },
    examples: ['use power chords', 'simplify to power chords'],
    tradition: 'Rock',
  },
  {
    id: createLexemeId('noun', 'quartal-harmony'),
    term: 'quartal harmony',
    variants: ['fourth chords', 'stacked fourths'],
    category: 'harmony',
    definition: 'Harmony built from stacked perfect fourths',
    semantics: { type: 'property', propertyOf: 'chord' },
    examples: ['use quartal harmony', 'voice in fourths'],
    tradition: 'Jazz/Contemporary',
  },
  {
    id: createLexemeId('noun', 'quintal-harmony'),
    term: 'quintal harmony',
    variants: ['fifth chords', 'stacked fifths'],
    category: 'harmony',
    definition: 'Harmony built from stacked perfect fifths',
    semantics: { type: 'property', propertyOf: 'chord' },
    examples: ['use quintal voicings'],
    tradition: 'Contemporary',
  },
  {
    id: createLexemeId('noun', 'cluster'),
    term: 'cluster',
    variants: ['tone cluster', 'note cluster'],
    category: 'harmony',
    definition: 'Chord of adjacent pitches (seconds)',
    semantics: { type: 'entity_ref', entityType: 'chord' },
    examples: ['add cluster chord', 'create dissonant cluster'],
    tradition: 'Contemporary classical',
  },
  {
    id: createLexemeId('noun', 'parallel-harmony'),
    term: 'parallel harmony',
    variants: ['planing', 'parallel motion'],
    category: 'harmony',
    definition: 'Chords moving in parallel motion',
    semantics: { type: 'pattern', patternType: 'harmonic' },
    examples: ['use parallel harmony', 'add parallel voicings'],
  },
  {
    id: createLexemeId('noun', 'contrary-motion'),
    term: 'contrary motion',
    variants: ['countermotion'],
    category: 'voice_leading',
    definition: 'Voices moving in opposite directions',
    semantics: { type: 'pattern', patternType: 'voice_leading' },
    examples: ['use contrary motion', 'resolve with contrary motion'],
  },
  {
    id: createLexemeId('noun', 'oblique-motion'),
    term: 'oblique motion',
    variants: ['static voice'],
    category: 'voice_leading',
    definition: 'One voice moves while another stays',
    semantics: { type: 'pattern', patternType: 'voice_leading' },
    examples: ['use oblique motion'],
  },
  {
    id: createLexemeId('noun', 'voice-crossing'),
    term: 'voice crossing',
    variants: ['crossed voices'],
    category: 'voice_leading',
    definition: 'Lower voice moves above higher voice',
    semantics: { type: 'pattern', patternType: 'voice_leading' },
    examples: ['avoid voice crossing', 'fix voice crossing'],
  },
  {
    id: createLexemeId('noun', 'voice-doubling'),
    term: 'voice doubling',
    variants: ['doubling', 'octave doubling'],
    category: 'voice_leading',
    definition: 'Same pitch class in multiple voices',
    semantics: { type: 'pattern', patternType: 'voice_leading' },
    examples: ['double the melody', 'avoid doubling the third'],
  },
  {
    id: createLexemeId('noun', 'parallel-fifths'),
    term: 'parallel fifths',
    variants: ['consecutive fifths', 'hidden fifths'],
    category: 'voice_leading',
    definition: 'Parallel motion in perfect fifths (typically avoided in classical)',
    semantics: { type: 'pattern', patternType: 'voice_leading' },
    examples: ['avoid parallel fifths', 'check for parallel fifths'],
    tradition: 'Western classical',
  },
  {
    id: createLexemeId('noun', 'parallel-octaves'),
    term: 'parallel octaves',
    variants: ['consecutive octaves'],
    category: 'voice_leading',
    definition: 'Parallel motion in octaves (typically avoided in classical)',
    semantics: { type: 'pattern', patternType: 'voice_leading' },
    examples: ['avoid parallel octaves'],
    tradition: 'Western classical',
  },

  // Melody nouns
  {
    id: createLexemeId('noun', 'melody'),
    term: 'melody',
    variants: ['tune', 'melodic line', 'theme'],
    category: 'melody',
    definition: 'Linear succession of pitches forming a recognizable tune',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['preserve the melody', 'vary the melody'],
  },
  {
    id: createLexemeId('noun', 'motif'),
    term: 'motif',
    variants: ['motive', 'cell', 'figure'],
    category: 'motif',
    definition: 'Short melodic or rhythmic idea',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['develop the motif', 'repeat the motif'],
  },
  {
    id: createLexemeId('noun', 'theme'),
    term: 'theme',
    variants: ['subject', 'main theme'],
    category: 'melody',
    definition: 'Principal melodic idea',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['state the theme', 'transform the theme'],
  },
  {
    id: createLexemeId('noun', 'subject'),
    term: 'subject',
    variants: ['fugue subject', 'main subject'],
    category: 'melody',
    definition: 'Main theme in fugue or fugato',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['introduce the subject', 'invert the subject'],
    tradition: 'Western classical',
  },
  {
    id: createLexemeId('noun', 'countersubject'),
    term: 'countersubject',
    variants: ['counter-subject'],
    category: 'melody',
    definition: 'Countermelody accompanying fugue subject',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add countersubject'],
    tradition: 'Western classical',
  },
  {
    id: createLexemeId('noun', 'sequence'),
    term: 'sequence',
    variants: ['melodic sequence', 'sequential pattern'],
    category: 'melody',
    definition: 'Melodic pattern repeated at different pitch levels',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['create a sequence', 'extend the sequence'],
  },
  {
    id: createLexemeId('noun', 'leap'),
    term: 'leap',
    variants: ['melodic leap', 'jump'],
    category: 'melody',
    definition: 'Melodic interval larger than a second',
    semantics: { type: 'property', propertyOf: 'melody' },
    examples: ['add leaps', 'smooth the leaps'],
  },
  {
    id: createLexemeId('noun', 'stepwise-motion'),
    term: 'stepwise motion',
    variants: ['conjunct motion', 'scalar motion'],
    category: 'melody',
    definition: 'Melodic movement by seconds',
    semantics: { type: 'property', propertyOf: 'melody' },
    examples: ['use stepwise motion', 'fill in stepwise'],
  },
  {
    id: createLexemeId('noun', 'contour'),
    term: 'contour',
    variants: ['melodic contour', 'shape', 'profile'],
    category: 'contour',
    definition: 'Overall shape of a melodic line',
    semantics: { type: 'property', propertyOf: 'melody' },
    examples: ['preserve the contour', 'mirror the contour'],
  },
  {
    id: createLexemeId('noun', 'arch'),
    term: 'arch',
    variants: ['arch shape', 'arc'],
    category: 'contour',
    definition: 'Melodic shape rising then falling',
    semantics: { type: 'property', propertyOf: 'melody' },
    examples: ['create arch contour', 'shape as arch'],
  },
  {
    id: createLexemeId('noun', 'climax'),
    term: 'climax',
    variants: ['peak', 'high point'],
    category: 'contour',
    definition: 'Highest or most intense point in a phrase',
    semantics: { type: 'entity_ref', entityType: 'timepoint' },
    examples: ['build to the climax', 'emphasize the climax'],
  },
  {
    id: createLexemeId('noun', 'anacrusis'),
    term: 'anacrusis',
    variants: ['pickup', 'upbeat', 'lead-in'],
    category: 'melody',
    definition: 'Notes before the first strong beat',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add anacrusis', 'shorten the pickup'],
  },
  {
    id: createLexemeId('noun', 'antecedent'),
    term: 'antecedent',
    variants: ['question phrase'],
    category: 'melody',
    definition: 'First phrase of a period, creating expectation',
    semantics: { type: 'entity_ref', entityType: 'phrase' },
    examples: ['shape the antecedent'],
    tradition: 'Western classical',
  },
  {
    id: createLexemeId('noun', 'consequent'),
    term: 'consequent',
    variants: ['answer phrase'],
    category: 'melody',
    definition: 'Second phrase of a period, providing resolution',
    semantics: { type: 'entity_ref', entityType: 'phrase' },
    examples: ['balance with consequent'],
    tradition: 'Western classical',
  },
  {
    id: createLexemeId('noun', 'call-and-response'),
    term: 'call and response',
    variants: ['call-response', 'question-answer'],
    category: 'melody',
    definition: 'Musical dialogue between two parts',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['use call and response', 'add response phrase'],
  },
  {
    id: createLexemeId('noun', 'melisma'),
    term: 'melisma',
    variants: ['melismatic passage', 'vocal run'],
    category: 'ornament',
    definition: 'Multiple notes sung on one syllable',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add melisma', 'simplify melismatic line'],
  },

  // Ornament nouns
  {
    id: createLexemeId('noun', 'ornament'),
    term: 'ornament',
    variants: ['embellishment', 'decoration'],
    category: 'ornament',
    definition: 'Decorative note or figure',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add ornaments', 'remove ornaments'],
  },
  {
    id: createLexemeId('noun', 'trill'),
    term: 'trill',
    variants: ['shake', 'rapid alternation'],
    category: 'ornament',
    definition: 'Rapid alternation between two adjacent pitches',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add trill', 'extend the trill'],
  },
  {
    id: createLexemeId('noun', 'mordent'),
    term: 'mordent',
    variants: ['upper mordent', 'lower mordent'],
    category: 'ornament',
    definition: 'Single rapid alternation with adjacent note',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add mordent'],
    tradition: 'Baroque',
  },
  {
    id: createLexemeId('noun', 'turn'),
    term: 'turn',
    variants: ['gruppetto'],
    category: 'ornament',
    definition: 'Ornament circling the main note',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add turn'],
    tradition: 'Classical',
  },
  {
    id: createLexemeId('noun', 'appoggiatura'),
    term: 'appoggiatura',
    variants: ['leaning note', 'grace note'],
    category: 'ornament',
    definition: 'Accented non-chord tone resolving by step',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add appoggiaturas'],
    tradition: 'Classical',
  },
  {
    id: createLexemeId('noun', 'grace-note'),
    term: 'grace note',
    variants: ['acciaccatura', 'crushed note'],
    category: 'ornament',
    definition: 'Very short ornamental note',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add grace notes', 'remove grace notes'],
  },
  {
    id: createLexemeId('noun', 'glissando'),
    term: 'glissando',
    variants: ['gliss', 'slide'],
    category: 'ornament',
    definition: 'Continuous pitch slide',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add glissando', 'create slide effect'],
  },
  {
    id: createLexemeId('noun', 'portamento'),
    term: 'portamento',
    variants: ['pitch bend', 'scoop'],
    category: 'ornament',
    definition: 'Smooth pitch transition',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add portamento', 'scoop into note'],
  },
  {
    id: createLexemeId('noun', 'vibrato'),
    term: 'vibrato',
    variants: ['pitch vibrato', 'tremolo'],
    category: 'ornament',
    definition: 'Periodic pitch oscillation',
    semantics: { type: 'quality', qualityDimension: 'expression' },
    examples: ['add vibrato', 'increase vibrato depth'],
  },
  {
    id: createLexemeId('noun', 'tremolo'),
    term: 'tremolo',
    variants: ['rapid repetition', 'finger tremolo'],
    category: 'ornament',
    definition: 'Rapid repetition of a note or alternation between notes',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add tremolo', 'use tremolo effect'],
  },
  {
    id: createLexemeId('noun', 'trill-chain'),
    term: 'trill chain',
    variants: ['sequential trills'],
    category: 'ornament',
    definition: 'Series of trills',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['create trill chain'],
  },
  {
    id: createLexemeId('noun', 'passing-tone'),
    term: 'passing tone',
    variants: ['passing note', 'PT'],
    category: 'ornament',
    definition: 'Non-chord tone connecting chord tones stepwise',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add passing tones', 'fill with passing notes'],
  },
  {
    id: createLexemeId('noun', 'neighbor-tone'),
    term: 'neighbor tone',
    variants: ['auxiliary note', 'NT'],
    category: 'ornament',
    definition: 'Non-chord tone a step away returning to original',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add neighbor tones'],
  },
  {
    id: createLexemeId('noun', 'anticipation'),
    term: 'anticipation',
    variants: ['anticipated note'],
    category: 'ornament',
    definition: 'Note of next chord sounded early',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add anticipations', 'anticipate the resolution'],
  },
  {
    id: createLexemeId('noun', 'escape-tone'),
    term: 'escape tone',
    variants: ['echappée'],
    category: 'ornament',
    definition: 'Non-chord tone approached by step, left by leap',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add escape tones'],
  },

  // Scale and mode nouns
  {
    id: createLexemeId('noun', 'scale'),
    term: 'scale',
    variants: ['pitch collection', 'tonal system'],
    category: 'scale_mode',
    definition: 'Ordered collection of pitches',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['change the scale', 'use different scale'],
  },
  {
    id: createLexemeId('noun', 'mode'),
    term: 'mode',
    variants: ['modal scale', 'church mode'],
    category: 'scale_mode',
    definition: 'Scale type distinguished by interval pattern',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use Dorian mode', 'shift to modal harmony'],
  },
  {
    id: createLexemeId('noun', 'major-scale'),
    term: 'major scale',
    variants: ['major', 'Ionian mode'],
    category: 'scale_mode',
    definition: 'Diatonic scale with major third: W-W-H-W-W-W-H',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use major scale', 'stay in major'],
  },
  {
    id: createLexemeId('noun', 'minor-scale'),
    term: 'minor scale',
    variants: ['minor', 'natural minor', 'Aeolian mode'],
    category: 'scale_mode',
    definition: 'Diatonic scale with minor third: W-H-W-W-H-W-W',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use minor scale', 'shift to minor'],
  },
  {
    id: createLexemeId('noun', 'harmonic-minor'),
    term: 'harmonic minor',
    variants: ['harmonic minor scale'],
    category: 'scale_mode',
    definition: 'Minor scale with raised seventh',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use harmonic minor'],
  },
  {
    id: createLexemeId('noun', 'melodic-minor'),
    term: 'melodic minor',
    variants: ['jazz minor'],
    category: 'scale_mode',
    definition: 'Minor scale with raised sixth and seventh',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use melodic minor', 'apply jazz minor'],
  },
  {
    id: createLexemeId('noun', 'dorian'),
    term: 'Dorian',
    variants: ['Dorian mode'],
    category: 'scale_mode',
    definition: 'Mode with minor third and major sixth',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use Dorian mode', 'shift to Dorian'],
  },
  {
    id: createLexemeId('noun', 'phrygian'),
    term: 'Phrygian',
    variants: ['Phrygian mode'],
    category: 'scale_mode',
    definition: 'Mode with minor second and minor third',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use Phrygian mode'],
  },
  {
    id: createLexemeId('noun', 'lydian'),
    term: 'Lydian',
    variants: ['Lydian mode'],
    category: 'scale_mode',
    definition: 'Mode with major third and augmented fourth',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use Lydian mode', 'brighten with Lydian'],
  },
  {
    id: createLexemeId('noun', 'mixolydian'),
    term: 'Mixolydian',
    variants: ['Mixolydian mode'],
    category: 'scale_mode',
    definition: 'Mode with major third and minor seventh',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use Mixolydian mode'],
  },
  {
    id: createLexemeId('noun', 'locrian'),
    term: 'Locrian',
    variants: ['Locrian mode'],
    category: 'scale_mode',
    definition: 'Mode with diminished fifth',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use Locrian mode'],
  },
  {
    id: createLexemeId('noun', 'pentatonic'),
    term: 'pentatonic',
    variants: ['pentatonic scale', 'five-note scale'],
    category: 'scale_mode',
    definition: 'Five-note scale',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use pentatonic scale', 'simplify to pentatonic'],
  },
  {
    id: createLexemeId('noun', 'blues-scale'),
    term: 'blues scale',
    variants: ['blue note scale'],
    category: 'scale_mode',
    definition: 'Pentatonic scale with added flat fifth',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use blues scale', 'add blue notes'],
    tradition: 'Blues',
  },
  {
    id: createLexemeId('noun', 'whole-tone-scale'),
    term: 'whole tone scale',
    variants: ['whole tone', 'augmented scale'],
    category: 'scale_mode',
    definition: 'Hexatonic scale of whole steps',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use whole tone scale'],
    tradition: 'Impressionist',
  },
  {
    id: createLexemeId('noun', 'diminished-scale'),
    term: 'diminished scale',
    variants: ['octatonic', 'whole-half', 'half-whole'],
    category: 'scale_mode',
    definition: 'Eight-note symmetrical scale alternating whole and half steps',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use diminished scale'],
    tradition: 'Jazz',
  },
  {
    id: createLexemeId('noun', 'chromatic'),
    term: 'chromatic',
    variants: ['chromatic scale', 'twelve-tone'],
    category: 'scale_mode',
    definition: 'All twelve pitches of equal temperament',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['add chromatic notes', 'use chromatic passing'],
  },
  {
    id: createLexemeId('noun', 'bebop-scale'),
    term: 'bebop scale',
    variants: ['bebop dominant', 'bebop major'],
    category: 'scale_mode',
    definition: 'Scale with added chromatic passing tone',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use bebop scale'],
    tradition: 'Jazz',
  },
  {
    id: createLexemeId('noun', 'altered-scale'),
    term: 'altered scale',
    variants: ['superlocrian', 'diminished whole tone'],
    category: 'scale_mode',
    definition: 'Seventh mode of melodic minor',
    semantics: { type: 'property', propertyOf: 'pitch' },
    examples: ['use altered scale over V7'],
    tradition: 'Jazz',
  },
];

// =============================================================================
// Exports
// =============================================================================

export const DOMAIN_NOUNS_BATCH_2 = HARMONY_NOUNS_CONTINUED;
