/**
 * GOFAI Domain Nouns — Batch 4: Articulation, Dynamics, Performance, Genre, Style
 *
 * Continuation with performance techniques and stylistic terminology.
 *
 * @module gofai/canon/domain-nouns-batch4
 */

import {
  createLexemeId,
} from './types';
import type { DomainNoun } from './domain-nouns';

// =============================================================================
// Articulation Nouns
// =============================================================================

const ARTICULATION_NOUNS: readonly DomainNoun[] = [
  {
    id: createLexemeId('noun', 'staccato'),
    term: 'staccato',
    variants: ['short', 'detached'],
    category: 'articulation',
    definition: 'Short, detached note articulation',
    semantics: { type: 'quality', qualityDimension: 'articulation' },
    examples: ['play staccato', 'make it more staccato'],
  },
  {
    id: createLexemeId('noun', 'legato'),
    term: 'legato',
    variants: ['smooth', 'connected'],
    category: 'articulation',
    definition: 'Smooth, connected note articulation',
    semantics: { type: 'quality', qualityDimension: 'articulation' },
    examples: ['play legato', 'smooth the phrase'],
  },
  {
    id: createLexemeId('noun', 'marcato'),
    term: 'marcato',
    variants: ['marked', 'accented'],
    category: 'articulation',
    definition: 'Strongly accented articulation',
    semantics: { type: 'quality', qualityDimension: 'articulation' },
    examples: ['add marcato', 'emphasize marcato notes'],
  },
  {
    id: createLexemeId('noun', 'tenuto'),
    term: 'tenuto',
    variants: ['held', 'sustained'],
    category: 'articulation',
    definition: 'Full value held articulation',
    semantics: { type: 'quality', qualityDimension: 'articulation' },
    examples: ['add tenuto', 'hold the notes'],
  },
  {
    id: createLexemeId('noun', 'accent'),
    term: 'accent',
    variants: ['emphasis', 'stress'],
    category: 'articulation',
    definition: 'Emphasis on specific notes',
    semantics: { type: 'quality', qualityDimension: 'articulation' },
    examples: ['add accents', 'accent the downbeats'],
  },
  {
    id: createLexemeId('noun', 'sforzando'),
    term: 'sforzando',
    variants: ['sfz', 'forced', 'sudden accent'],
    category: 'articulation',
    definition: 'Sudden strong accent',
    semantics: { type: 'quality', qualityDimension: 'articulation' },
    examples: ['add sforzando', 'accent suddenly'],
  },
  {
    id: createLexemeId('noun', 'pizzicato'),
    term: 'pizzicato',
    variants: ['pizz', 'plucked'],
    category: 'technique',
    definition: 'Plucked string technique',
    semantics: { type: 'quality', qualityDimension: 'technique' },
    examples: ['use pizzicato', 'pluck the strings'],
    tradition: 'String instruments',
  },
  {
    id: createLexemeId('noun', 'arco'),
    term: 'arco',
    variants: ['bowed'],
    category: 'technique',
    definition: 'Bowed string technique',
    semantics: { type: 'quality', qualityDimension: 'technique' },
    examples: ['return to arco', 'bow the strings'],
    tradition: 'String instruments',
  },
  {
    id: createLexemeId('noun', 'col-legno'),
    term: 'col legno',
    variants: ['with the wood'],
    category: 'technique',
    definition: 'Striking strings with bow stick',
    semantics: { type: 'quality', qualityDimension: 'technique' },
    examples: ['use col legno'],
    tradition: 'String instruments',
  },
  {
    id: createLexemeId('noun', 'sul-ponticello'),
    term: 'sul ponticello',
    variants: ['near the bridge'],
    category: 'technique',
    definition: 'Bowing near bridge for glassy tone',
    semantics: { type: 'quality', qualityDimension: 'technique' },
    examples: ['play sul ponticello'],
    tradition: 'String instruments',
  },
  {
    id: createLexemeId('noun', 'sul-tasto'),
    term: 'sul tasto',
    variants: ['on the fingerboard'],
    category: 'technique',
    definition: 'Bowing over fingerboard for soft tone',
    semantics: { type: 'quality', qualityDimension: 'technique' },
    examples: ['play sul tasto'],
    tradition: 'String instruments',
  },
  {
    id: createLexemeId('noun', 'harmonics'),
    term: 'harmonics',
    variants: ['natural harmonics', 'artificial harmonics'],
    category: 'technique',
    definition: 'High overtones produced by light string touch',
    semantics: { type: 'quality', qualityDimension: 'technique' },
    examples: ['add harmonics', 'use natural harmonics'],
  },
  {
    id: createLexemeId('noun', 'flutter-tongue'),
    term: 'flutter tongue',
    variants: ['flutter-tonguing', 'fluttertongue'],
    category: 'technique',
    definition: 'Wind technique rolling R sound',
    semantics: { type: 'quality', qualityDimension: 'technique' },
    examples: ['use flutter tongue'],
    tradition: 'Wind instruments',
  },
  {
    id: createLexemeId('noun', 'double-tongue'),
    term: 'double tongue',
    variants: ['double-tonguing'],
    category: 'technique',
    definition: 'Rapid articulation technique for winds',
    semantics: { type: 'quality', qualityDimension: 'technique' },
    examples: ['use double tonguing'],
    tradition: 'Wind instruments',
  },
  {
    id: createLexemeId('noun', 'slap-tongue'),
    term: 'slap tongue',
    variants: ['tongue slap'],
    category: 'technique',
    definition: 'Percussive wind technique',
    semantics: { type: 'quality', qualityDimension: 'technique' },
    examples: ['add slap tongue'],
    tradition: 'Wind instruments',
  },
  {
    id: createLexemeId('noun', 'mute'),
    term: 'mute',
    variants: ['muted', 'con sordino'],
    category: 'technique',
    definition: 'Device or technique reducing volume and altering timbre',
    semantics: { type: 'quality', qualityDimension: 'technique' },
    examples: ['add mute', 'use muted brass'],
  },
  {
    id: createLexemeId('noun', 'ghost-note'),
    term: 'ghost note',
    variants: ['dead stroke', 'muted note'],
    category: 'technique',
    definition: 'Very soft, barely audible note',
    semantics: { type: 'quality', qualityDimension: 'articulation' },
    examples: ['add ghost notes', 'use ghost notes on snare'],
  },
  {
    id: createLexemeId('noun', 'flam'),
    term: 'flam',
    variants: ['drag'],
    category: 'technique',
    definition: 'Drum rudiment with grace note',
    semantics: { type: 'pattern', patternType: 'rhythmic' },
    examples: ['add flams', 'use flam on snare'],
    tradition: 'Percussion',
  },
  {
    id: createLexemeId('noun', 'roll'),
    term: 'roll',
    variants: ['drum roll', 'snare roll'],
    category: 'technique',
    definition: 'Sustained rapid percussion strokes',
    semantics: { type: 'pattern', patternType: 'rhythmic' },
    examples: ['add drum roll', 'build with roll'],
    tradition: 'Percussion',
  },
  {
    id: createLexemeId('noun', 'rim-shot'),
    term: 'rim shot',
    variants: ['rimshot'],
    category: 'technique',
    definition: 'Hitting rim and head simultaneously',
    semantics: { type: 'quality', qualityDimension: 'technique' },
    examples: ['add rim shots', 'accent with rim shot'],
    tradition: 'Percussion',
  },

  // Dynamics nouns
  {
    id: createLexemeId('noun', 'dynamics'),
    term: 'dynamics',
    variants: ['volume changes', 'loudness'],
    category: 'dynamics',
    definition: 'Variations in loudness',
    semantics: { type: 'quality', qualityDimension: 'dynamics' },
    examples: ['adjust dynamics', 'add dynamic contrast'],
  },
  {
    id: createLexemeId('noun', 'crescendo'),
    term: 'crescendo',
    variants: ['cresc', 'getting louder'],
    category: 'dynamics',
    definition: 'Gradual increase in volume',
    semantics: { type: 'process', processType: 'dynamic' },
    examples: ['add crescendo', 'build with crescendo'],
  },
  {
    id: createLexemeId('noun', 'decrescendo'),
    term: 'decrescendo',
    variants: ['decresc', 'diminuendo', 'dim', 'getting softer'],
    category: 'dynamics',
    definition: 'Gradual decrease in volume',
    semantics: { type: 'process', processType: 'dynamic' },
    examples: ['add decrescendo', 'fade with diminuendo'],
  },
  {
    id: createLexemeId('noun', 'swell'),
    term: 'swell',
    variants: ['dynamic swell'],
    category: 'dynamics',
    definition: 'Crescendo followed by decrescendo',
    semantics: { type: 'process', processType: 'dynamic' },
    examples: ['add swell', 'create dynamic swell'],
  },
  {
    id: createLexemeId('noun', 'subito'),
    term: 'subito',
    variants: ['suddenly', 'immediate change'],
    category: 'dynamics',
    definition: 'Sudden dynamic change',
    semantics: { type: 'quality', qualityDimension: 'dynamics' },
    examples: ['drop subito piano', 'sudden dynamic shift'],
  },

  // Performance expression nouns
  {
    id: createLexemeId('noun', 'rubato'),
    term: 'rubato',
    variants: ['tempo rubato', 'flexible tempo'],
    category: 'expression',
    definition: 'Expressive timing flexibility',
    semantics: { type: 'quality', qualityDimension: 'timing' },
    examples: ['add rubato', 'play with rubato'],
  },
  {
    id: createLexemeId('noun', 'agogic'),
    term: 'agogic accent',
    variants: ['durational accent'],
    category: 'expression',
    definition: 'Emphasis through duration lengthening',
    semantics: { type: 'quality', qualityDimension: 'timing' },
    examples: ['add agogic accent', 'lengthen for emphasis'],
  },
  {
    id: createLexemeId('noun', 'phrasing'),
    term: 'phrasing',
    variants: ['phrase shaping', 'musical phrasing'],
    category: 'expression',
    definition: 'Shaping of musical phrases',
    semantics: { type: 'quality', qualityDimension: 'expression' },
    examples: ['improve phrasing', 'shape the phrase'],
  },
  {
    id: createLexemeId('noun', 'expression'),
    term: 'expression',
    variants: ['musicality', 'emotional content'],
    category: 'expression',
    definition: 'Conveyance of emotion and character',
    semantics: { type: 'quality', qualityDimension: 'expression' },
    examples: ['add more expression', 'play with expression'],
  },
  {
    id: createLexemeId('noun', 'humanization'),
    term: 'humanization',
    variants: ['human feel', 'natural variation'],
    category: 'expression',
    definition: 'Subtle timing and velocity variations',
    semantics: { type: 'quality', qualityDimension: 'timing' },
    examples: ['add humanization', 'humanize the drums'],
  },

  // Genre nouns
  {
    id: createLexemeId('noun', 'jazz'),
    term: 'jazz',
    variants: ['jazz style', 'jazz idiom'],
    category: 'genre',
    definition: 'American improvisational music tradition',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['make it more jazz', 'use jazz harmony'],
    tradition: 'Jazz',
  },
  {
    id: createLexemeId('noun', 'blues'),
    term: 'blues',
    variants: ['blues style', 'blues idiom'],
    category: 'genre',
    definition: 'African-American roots music form',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['add blues feel', 'use blues scale'],
    tradition: 'Blues',
  },
  {
    id: createLexemeId('noun', 'funk'),
    term: 'funk',
    variants: ['funk style', 'funk groove'],
    category: 'genre',
    definition: 'Syncopated groove-based music',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['make it funkier', 'add funk groove'],
    tradition: 'Funk',
  },
  {
    id: createLexemeId('noun', 'rock'),
    term: 'rock',
    variants: ['rock music', 'rock style'],
    category: 'genre',
    definition: 'Electric guitar-based popular music',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['make it more rock', 'use rock feel'],
    tradition: 'Rock',
  },
  {
    id: createLexemeId('noun', 'hip-hop'),
    term: 'hip-hop',
    variants: ['hip hop', 'rap', 'urban'],
    category: 'genre',
    definition: 'Rhythmic spoken vocal over beats',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['use hip-hop beat', 'add hip-hop feel'],
    tradition: 'Hip-hop',
  },
  {
    id: createLexemeId('noun', 'edm'),
    term: 'EDM',
    variants: ['electronic dance music', 'dance music'],
    category: 'genre',
    definition: 'Electronic music for dancing',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['make it more EDM', 'use EDM production'],
    tradition: 'Electronic',
  },
  {
    id: createLexemeId('noun', 'house'),
    term: 'house',
    variants: ['house music', 'four-on-floor'],
    category: 'genre',
    definition: 'Four-on-the-floor electronic dance music',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['use house beat', 'make it house'],
    tradition: 'Electronic',
  },
  {
    id: createLexemeId('noun', 'techno'),
    term: 'techno',
    variants: ['techno music'],
    category: 'genre',
    definition: 'Repetitive electronic dance music',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['use techno groove', 'make it techno'],
    tradition: 'Electronic',
  },
  {
    id: createLexemeId('noun', 'dubstep'),
    term: 'dubstep',
    variants: ['dub step'],
    category: 'genre',
    definition: 'Electronic music with heavy bass and syncopation',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['use dubstep wobble', 'add dubstep feel'],
    tradition: 'Electronic',
  },
  {
    id: createLexemeId('noun', 'trap'),
    term: 'trap',
    variants: ['trap music'],
    category: 'genre',
    definition: 'Hip-hop subgenre with distinctive hi-hat patterns',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['use trap hi-hats', 'make it trap'],
    tradition: 'Hip-hop',
  },
  {
    id: createLexemeId('noun', 'drum-and-bass'),
    term: 'drum and bass',
    variants: ['DnB', 'jungle'],
    category: 'genre',
    definition: 'Fast breakbeat electronic music',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['use DnB tempo', 'make it drum and bass'],
    tradition: 'Electronic',
  },
  {
    id: createLexemeId('noun', 'ambient'),
    term: 'ambient',
    variants: ['ambient music', 'atmospheric'],
    category: 'genre',
    definition: 'Atmospheric background music',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['make it more ambient', 'add ambient texture'],
    tradition: 'Electronic',
  },
  {
    id: createLexemeId('noun', 'lofi'),
    term: 'lo-fi',
    variants: ['lofi', 'low fidelity', 'lo-fi hip hop'],
    category: 'genre',
    definition: 'Aesthetically imperfect recording quality',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['make it lo-fi', 'add lo-fi texture'],
    tradition: 'Hip-hop',
  },
  {
    id: createLexemeId('noun', 'reggae'),
    term: 'reggae',
    variants: ['reggae music'],
    category: 'genre',
    definition: 'Jamaican music with offbeat rhythms',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['use reggae feel', 'add reggae rhythm'],
    tradition: 'Reggae',
  },
  {
    id: createLexemeId('noun', 'gospel'),
    term: 'gospel',
    variants: ['gospel music'],
    category: 'genre',
    definition: 'African-American religious music',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['add gospel feel', 'use gospel harmonies'],
    tradition: 'Gospel',
  },
  {
    id: createLexemeId('noun', 'country'),
    term: 'country',
    variants: ['country music', 'country western'],
    category: 'genre',
    definition: 'American rural popular music',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['make it country', 'add country feel'],
    tradition: 'Country',
  },
  {
    id: createLexemeId('noun', 'folk'),
    term: 'folk',
    variants: ['folk music', 'traditional'],
    category: 'genre',
    definition: 'Traditional music of a community',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['use folk style', 'simplify to folk'],
    tradition: 'Folk',
  },
  {
    id: createLexemeId('noun', 'classical'),
    term: 'classical',
    variants: ['classical music', 'art music'],
    category: 'genre',
    definition: 'Western art music tradition',
    semantics: { type: 'property', propertyOf: 'style' },
    examples: ['use classical harmony', 'make it classical'],
    tradition: 'Western classical',
  },

  // Style and device nouns
  {
    id: createLexemeId('noun', 'call-response'),
    term: 'call-response',
    variants: ['call and response', 'antiphonal'],
    category: 'idiom',
    definition: 'Alternating phrases between voices',
    semantics: { type: 'pattern', patternType: 'structural' },
    examples: ['use call and response', 'add response phrase'],
  },
  {
    id: createLexemeId('noun', 'question-answer'),
    term: 'question-answer',
    variants: ['Q&A phrase', 'interrogative phrase'],
    category: 'idiom',
    definition: 'Phrase creating expectation followed by resolution',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['create question-answer', 'balance question and answer'],
  },
  {
    id: createLexemeId('noun', 'walking-bass'),
    term: 'walking bass',
    variants: ['walking bassline'],
    category: 'idiom',
    definition: 'Stepwise quarter-note bass pattern',
    semantics: { type: 'pattern', patternType: 'rhythmic' },
    examples: ['add walking bass', 'use walking bassline'],
    tradition: 'Jazz',
  },
  {
    id: createLexemeId('noun', 'comping'),
    term: 'comping',
    variants: ['accompaniment', 'chord comping'],
    category: 'idiom',
    definition: 'Rhythmic chord accompaniment',
    semantics: { type: 'pattern', patternType: 'rhythmic' },
    examples: ['add comping pattern', 'use jazz comping'],
    tradition: 'Jazz',
  },
  {
    id: createLexemeId('noun', 'pedal-point'),
    term: 'pedal point',
    variants: ['pedal', 'drone bass'],
    category: 'device',
    definition: 'Sustained bass note under changing harmony',
    semantics: { type: 'pattern', patternType: 'harmonic' },
    examples: ['add pedal point', 'sustain pedal on tonic'],
  },
  {
    id: createLexemeId('noun', 'ostinato-bass'),
    term: 'ostinato bass',
    variants: ['ground bass', 'basso ostinato'],
    category: 'device',
    definition: 'Repeated bass pattern',
    semantics: { type: 'pattern', patternType: 'rhythmic' },
    examples: ['use ostinato bass', 'repeat bass pattern'],
  },
  {
    id: createLexemeId('noun', 'alberti-bass'),
    term: 'Alberti bass',
    variants: ['broken chord accompaniment'],
    category: 'device',
    definition: 'Broken chord pattern: low-high-middle-high',
    semantics: { type: 'pattern', patternType: 'rhythmic' },
    examples: ['use Alberti bass'],
    tradition: 'Classical',
  },
  {
    id: createLexemeId('noun', 'arpeggio'),
    term: 'arpeggio',
    variants: ['broken chord', 'arpeggiation'],
    category: 'device',
    definition: 'Notes of chord played in succession',
    semantics: { type: 'pattern', patternType: 'melodic' },
    examples: ['add arpeggio', 'arpeggiate the chords'],
  },
  {
    id: createLexemeId('noun', 'block-chord'),
    term: 'block chord',
    variants: ['block voicing', 'locked hands'],
    category: 'device',
    definition: 'Melody harmonized in parallel chords',
    semantics: { type: 'pattern', patternType: 'harmonic' },
    examples: ['use block chords', 'harmonize in blocks'],
    tradition: 'Jazz',
  },
];

// =============================================================================
// Exports
// =============================================================================

export const DOMAIN_NOUNS_BATCH_4 = ARTICULATION_NOUNS;
