import { defineConfig } from 'vitepress';

export default defineConfig({
  title: 'Cardplay',
  description: 'Docs and internal plan',
  themeConfig: {
    nav: [{ text: 'Plan', link: '/plan' }],
    search: {
      provider: 'local',
    },
    sidebar: [
      { text: 'Home', link: '/' },
      { text: 'Plan', link: '/plan' },
      { text: 'Architecture', link: '/architecture' },
      { text: 'Glossary', link: '/glossary' },
      { text: 'Debugging', link: '/debugging' },
      { text: 'WASM', link: '/wasm' },
      { text: 'CardScript', link: '/cardscript' },
      { text: 'AI: Index', link: '/ai/' },
      { text: 'AI: Architecture', link: '/ai/architecture' },
      { text: 'AI: Prolog engine choice', link: '/ai/prolog-engine-choice' },
      { text: 'AI: Prolog deck reasoning', link: '/ai/prolog-deck-reasoning' },
      { text: 'AI: Prolog reference', link: '/ai/prolog-reference' },
      { text: 'AI: Learning', link: '/ai/learning' },
      { text: 'AI: Workflow planning', link: '/ai/workflow-planning' },
      { text: 'AI: Project analysis', link: '/ai/project-analysis' },
      { text: 'AI: KB architecture', link: '/ai/kb-architecture' },
      { text: 'AI: Predicate signatures', link: '/ai/predicate-signatures' },
      { text: 'AI: Performance', link: '/ai/performance' },
      { text: 'AI: Privacy', link: '/ai/privacy' },
      { text: 'AI: Troubleshooting', link: '/ai/troubleshooting' },
      { text: 'AI: FAQ', link: '/ai/faq' },
      { text: 'AI: Advisor', link: '/ai/ai-advisor' },
      { text: 'AI: Harmony examples', link: '/ai/harmony-examples' },
      { text: 'AI: Personas', link: '/ai/personas/' },
      { text: 'Release', link: '/release' },
      { text: 'Coding style', link: '/coding-style' },
      { text: 'Policies: npm audit', link: '/policies/npm-audit' },
      { text: 'Policies: dependency updates', link: '/policies/dependency-updates' },
    ],
  },
});
