/**
 * Implicature and Default Model
 *
 * Step 039 [Prag]: Specify an implicature/default model (Gricean/QUD):
 * what "keep tempo steady" implies absent explicit BPM changes.
 *
 * ## What Are Implicatures?
 *
 * Implicatures are meanings that are CONVEYED but not SAID. In music
 * editing, users frequently convey more than their words explicitly state:
 *
 * - "Keep tempo steady" IMPLIES: don't insert ritardandos, don't change
 *   time signature, don't add tempo automation. But the user only SAID
 *   "keep tempo steady."
 *
 * - "Make it tighter" IMPLIES: the current version is too loose/sloppy,
 *   and the user wants quantization or timing cleanup. But the user
 *   didn't explicitly say what mechanism to use.
 *
 * - "Just fix the drums" IMPLIES: everything else should be left alone.
 *   The word "just" generates a conversational implicature of exclusivity.
 *
 * ## Gricean Maxims in Music Editing
 *
 * The system follows Gricean cooperative principles:
 *
 * 1. **Quality**: Only make changes the system is confident about
 * 2. **Quantity**: Don't do more than asked (least-change principle)
 * 3. **Relevance**: Changes should relate to the stated goal
 * 4. **Manner**: Be clear about what was done and why
 *
 * ## QUD (Question Under Discussion)
 *
 * The QUD model tracks what the current "question" in the dialogue is.
 * This helps interpret ambiguous utterances:
 *
 * - If the QUD is "How should the chorus sound?", then "brighter" is
 *   interpreted relative to the chorus, not globally.
 * - If the QUD is "What's wrong with the mix?", then "the bass" is
 *   interpreted as identifying a problem, not requesting an action.
 *
 * ## Design Principles
 *
 * 1. **Implicatures are default bindings**: They map underspecified
 *    language to specific constraints/actions using defaults that
 *    are inspectable and user-overridable.
 *
 * 2. **Defaults are explicit**: Every default interpretation is
 *    documented in the canon with its provenance and rationale.
 *
 * 3. **Defaults can be overridden**: The user can say "I know I said
 *    'steady tempo' but actually vary it for expression" to override.
 *
 * 4. **The system shows its defaults**: When a default is applied,
 *    the preview shows "Using default: 'steady tempo' → no tempo
 *    changes, no ritardando, no time signature changes."
 *
 * @module gofai/pragmatics/implicature-model
 */

// =============================================================================
// Implicature Types
// =============================================================================

/**
 * Types of conversational implicature recognized in music editing.
 */
export type ImplicatureType =
  | 'scalar'           // "some" → not all; "a bit" → not a lot
  | 'exclusivity'      // "just/only X" → nothing else
  | 'sufficiency'      // "enough" → no more needed
  | 'insufficiency'    // "still too X" → need more change
  | 'relevance'        // Topic continuity from prior turn
  | 'manner'           // "carefully" → with constraints
  | 'quality'          // "I think" → low confidence
  | 'quantity';        // Short utterance → minimal change

/**
 * A detected implicature in an utterance.
 */
export interface Implicature {
  /** The type of implicature. */
  readonly type: ImplicatureType;
  /** The trigger word/phrase that generated it. */
  readonly trigger: string;
  /** What the implicature conveys (the default binding). */
  readonly conveyance: ImplicatureConveyance;
  /** Whether this implicature is cancellable (most are). */
  readonly cancellable: boolean;
  /** Confidence in this implicature. */
  readonly confidence: 'high' | 'medium' | 'low';
  /** How the user can cancel/override this implicature. */
  readonly overrideHint: string;
}

/**
 * What an implicature conveys — the default binding it generates.
 */
export type ImplicatureConveyance =
  | { readonly kind: 'constraint'; readonly constraint: ImplicatureConstraint }
  | { readonly kind: 'preference'; readonly preference: ImplicaturePreference }
  | { readonly kind: 'scope_restriction'; readonly restriction: string }
  | { readonly kind: 'degree_bound'; readonly bound: DegreeBound }
  | { readonly kind: 'topic_continuation'; readonly topic: string };

/**
 * A constraint generated by an implicature.
 */
export interface ImplicatureConstraint {
  /** What to constrain. */
  readonly target: string;
  /** How to constrain it. */
  readonly mode: 'preserve' | 'ceiling' | 'floor' | 'exclude';
  /** Whether this constraint is hard or soft. */
  readonly hard: boolean;
  /** Human-readable description. */
  readonly description: string;
}

/**
 * A preference generated by an implicature.
 */
export interface ImplicaturePreference {
  /** What the preference is about. */
  readonly axis: string;
  /** The preferred direction. */
  readonly direction: 'increase' | 'decrease' | 'maintain';
  /** Weight of the preference. */
  readonly weight: 'strong' | 'moderate' | 'weak';
  /** Human-readable description. */
  readonly description: string;
}

/**
 * A degree bound generated by scalar implicature.
 */
export interface DegreeBound {
  /** Upper or lower bound. */
  readonly boundType: 'upper' | 'lower';
  /** The degree value. */
  readonly value: string;
  /** Description. */
  readonly description: string;
}


// =============================================================================
// Canonical Default Interpretations
// =============================================================================

/**
 * A canonical default interpretation: maps a common phrase to
 * its default set of constraints/preferences/actions.
 *
 * These are the "no-magic" defaults referenced in Step 019 [Infra].
 * Every default is inspectable, documented, and user-overridable.
 */
export interface DefaultInterpretation {
  /** Unique identifier. */
  readonly id: string;
  /** The trigger phrase (normalized). */
  readonly phrase: string;
  /** Variant phrasings that map to the same default. */
  readonly variants: readonly string[];
  /** What constraints this phrase implies. */
  readonly impliedConstraints: readonly ImplicatureConstraint[];
  /** What preferences this phrase implies. */
  readonly impliedPreferences: readonly ImplicaturePreference[];
  /** Rationale for this default. */
  readonly rationale: string;
  /** How the user can override this default. */
  readonly overrideExamples: readonly string[];
}

/**
 * The canonical table of default interpretations.
 *
 * This is the SSOT for what common phrases imply in GOFAI Music+.
 * It is deliberately inspectable and documented per Step 019.
 */
export const DEFAULT_INTERPRETATIONS: readonly DefaultInterpretation[] = [

  // --- Tempo/timing defaults ---
  {
    id: 'default:keep-tempo-steady',
    phrase: 'keep tempo steady',
    variants: [
      'keep the tempo steady',
      'steady tempo',
      'constant tempo',
      'don\'t change the tempo',
      'maintain tempo',
      'same tempo throughout',
      'no tempo changes',
    ],
    impliedConstraints: [
      {
        target: 'tempo',
        mode: 'preserve',
        hard: true,
        description: 'No BPM changes',
      },
      {
        target: 'tempo_automation',
        mode: 'exclude',
        hard: true,
        description: 'No tempo automation curves',
      },
      {
        target: 'ritardando',
        mode: 'exclude',
        hard: true,
        description: 'No ritardando or accelerando',
      },
      {
        target: 'time_signature',
        mode: 'preserve',
        hard: false,
        description: 'No time signature changes (soft — user may intend only BPM)',
      },
    ],
    impliedPreferences: [],
    rationale: '"Steady" in tempo context implies no temporal variation of any kind, including automation and expressive tempo changes.',
    overrideExamples: [
      '"Keep the BPM the same but allow ritardando at the end"',
      '"Steady tempo except for a natural rallentando before the chorus"',
    ],
  },

  // --- Groove defaults ---
  {
    id: 'default:tighter-groove',
    phrase: 'tighter groove',
    variants: [
      'make it tighter',
      'tighten the groove',
      'lock in the groove',
      'clean up the timing',
      'more locked in',
    ],
    impliedConstraints: [],
    impliedPreferences: [
      {
        axis: 'groove_tightness',
        direction: 'increase',
        weight: 'strong',
        description: 'Increase quantization strength / reduce timing variance',
      },
      {
        axis: 'microtiming_variance',
        direction: 'decrease',
        weight: 'moderate',
        description: 'Reduce microtiming deviations',
      },
    ],
    rationale: '"Tighter groove" defaults to timing quantization and microtiming reduction. It does NOT default to compression or mix changes.',
    overrideExamples: [
      '"Tighter groove by compressing the drums more"',
      '"Tighter but keep the human feel"',
    ],
  },

  // --- Energy defaults ---
  {
    id: 'default:more-energy',
    phrase: 'more energy',
    variants: [
      'add energy',
      'more energetic',
      'pump it up',
      'give it energy',
      'liven it up',
      'make it livelier',
    ],
    impliedConstraints: [],
    impliedPreferences: [
      {
        axis: 'density',
        direction: 'increase',
        weight: 'moderate',
        description: 'Add rhythmic/harmonic density',
      },
      {
        axis: 'dynamics',
        direction: 'increase',
        weight: 'moderate',
        description: 'Increase dynamic level',
      },
      {
        axis: 'rhythmic_activity',
        direction: 'increase',
        weight: 'moderate',
        description: 'More rhythmic activity in layers',
      },
    ],
    rationale: '"More energy" is a multi-axis goal. Defaults to density + dynamics + rhythmic activity. Production changes (compression, EQ) are not implied unless the user mentions them.',
    overrideExamples: [
      '"More energy through higher dynamics, not more layers"',
      '"Energy from the drums specifically"',
    ],
  },

  // --- Preservation defaults ---
  {
    id: 'default:keep-melody',
    phrase: 'keep the melody',
    variants: [
      'preserve the melody',
      'don\'t change the melody',
      'leave the melody alone',
      'melody stays the same',
      'keep melody intact',
    ],
    impliedConstraints: [
      {
        target: 'melody_pitch',
        mode: 'preserve',
        hard: true,
        description: 'Melody pitch sequence is preserved exactly',
      },
      {
        target: 'melody_rhythm',
        mode: 'preserve',
        hard: true,
        description: 'Melody rhythm is preserved exactly',
      },
    ],
    impliedPreferences: [
      {
        axis: 'melody_articulation',
        direction: 'maintain',
        weight: 'moderate',
        description: 'Prefer to also maintain articulation (soft)',
      },
    ],
    rationale: '"Keep the melody" defaults to EXACT preservation of pitch and rhythm. Articulation preservation is a soft preference. The user can relax to "recognizable" or "functional" explicitly.',
    overrideExamples: [
      '"Keep the melody recognizable but allow embellishment"',
      '"Keep the melody functional — same harmonic function, different notes OK"',
    ],
  },

  // --- Scope defaults ---
  {
    id: 'default:just-fix',
    phrase: 'just fix',
    variants: [
      'just fix the',
      'only fix the',
      'just change the',
      'only touch the',
    ],
    impliedConstraints: [
      {
        target: 'everything_else',
        mode: 'preserve',
        hard: true,
        description: '"Just" implies everything else is preserved (exclusivity implicature)',
      },
    ],
    impliedPreferences: [
      {
        axis: 'edit_scope',
        direction: 'decrease',
        weight: 'strong',
        description: 'Minimize the scope of changes (least-change principle)',
      },
    ],
    rationale: '"Just" is a focus particle that generates an exclusivity implicature: ONLY the named target should change. Everything else should be preserved.',
    overrideExamples: [
      '"Fix the drums and also clean up the bass while you\'re at it"',
    ],
  },

  // --- Simplification defaults ---
  {
    id: 'default:simplify',
    phrase: 'simplify',
    variants: [
      'simplify it',
      'make it simpler',
      'less busy',
      'less going on',
      'strip it back',
      'thin it out',
      'declutter',
    ],
    impliedConstraints: [],
    impliedPreferences: [
      {
        axis: 'density',
        direction: 'decrease',
        weight: 'strong',
        description: 'Reduce number of simultaneous elements',
      },
      {
        axis: 'rhythmic_complexity',
        direction: 'decrease',
        weight: 'moderate',
        description: 'Reduce rhythmic complexity',
      },
      {
        axis: 'harmonic_complexity',
        direction: 'decrease',
        weight: 'weak',
        description: 'Optionally simplify harmonies (weak default)',
      },
    ],
    rationale: '"Simplify" defaults to density reduction and rhythmic simplification. Harmonic simplification is a weak default — most users mean arrangement, not reharmonization.',
    overrideExamples: [
      '"Simplify the harmony specifically"',
      '"Simplify by removing the pads and extra percussion"',
    ],
  },

  // --- Space/air defaults ---
  {
    id: 'default:more-space',
    phrase: 'more space',
    variants: [
      'give it more space',
      'more room',
      'let it breathe',
      'more breathing room',
      'open it up',
    ],
    impliedConstraints: [],
    impliedPreferences: [
      {
        axis: 'density',
        direction: 'decrease',
        weight: 'moderate',
        description: 'Reduce arrangement density',
      },
      {
        axis: 'reverb_depth',
        direction: 'increase',
        weight: 'weak',
        description: 'Possibly add spatial effects (weak default — ambiguous axis)',
      },
      {
        axis: 'dynamic_range',
        direction: 'increase',
        weight: 'weak',
        description: 'Possibly increase dynamic range (weak default)',
      },
    ],
    rationale: '"More space" is ambiguous between arrangement density, reverb/spatial effects, and dynamic range. Arrangement density is the safest default; reverb and dynamics are weak preferences that may trigger clarification.',
    overrideExamples: [
      '"More space through reverb"',
      '"More space by thinning the arrangement"',
      '"Let it breathe dynamically — less compression"',
    ],
  },

  // --- Warmth defaults ---
  {
    id: 'default:warmer',
    phrase: 'warmer',
    variants: [
      'make it warmer',
      'warm it up',
      'add warmth',
      'more warmth',
    ],
    impliedConstraints: [],
    impliedPreferences: [
      {
        axis: 'brightness',
        direction: 'decrease',
        weight: 'moderate',
        description: 'Reduce high-frequency harshness',
      },
      {
        axis: 'low_mid_presence',
        direction: 'increase',
        weight: 'moderate',
        description: 'Boost low-mid frequencies for warmth',
      },
      {
        axis: 'saturation',
        direction: 'increase',
        weight: 'weak',
        description: 'Possibly add gentle saturation (weak default)',
      },
    ],
    rationale: '"Warmer" most commonly means spectral warmth (less highs, more low-mids). Saturation is a secondary mechanism. Harmonic warmth (chord voicings) is NOT the default — it requires explicit mention.',
    overrideExamples: [
      '"Warm it up harmonically — use warmer voicings"',
      '"Add warmth through tape saturation"',
    ],
  },
];


// =============================================================================
// QUD (Question Under Discussion) Model
// =============================================================================

/**
 * The current Question Under Discussion.
 *
 * The QUD tracks what the conversation is "about" at any given point.
 * This affects how ambiguous utterances are interpreted.
 */
export interface QuestionUnderDiscussion {
  /** The current QUD text (informal). */
  readonly question: string;
  /** What entity/scope the QUD is about. */
  readonly aboutScope: string | undefined;
  /** What axis/property the QUD is about. */
  readonly aboutAxis: string | undefined;
  /** When this QUD was established. */
  readonly establishedAtTurn: number;
  /** Whether this QUD is still active. */
  readonly active: boolean;
}

/**
 * How QUD affects interpretation.
 *
 * When a QUD is active, underspecified utterances inherit the QUD's
 * scope and topic. For example:
 *
 * - QUD: "How should the chorus sound?"
 * - User: "Brighter"
 * - Resolution: increase(brightness, scope=chorus)
 *   (chorus is inherited from QUD)
 */
export interface QUDEffect {
  /** The QUD that produced this effect. */
  readonly qud: QuestionUnderDiscussion;
  /** What scope was inherited from the QUD. */
  readonly inheritedScope: string | undefined;
  /** What axis/topic was inherited. */
  readonly inheritedAxis: string | undefined;
  /** Human-readable explanation. */
  readonly explanation: string;
}

/**
 * Update the QUD based on a new utterance.
 *
 * QUD transitions:
 * - Explicit questions set a new QUD
 * - Topic-continuing utterances maintain the QUD
 * - Topic-shifting utterances replace the QUD
 * - Resolved/applied plans may close a QUD
 */
export function updateQUD(
  currentQUD: QuestionUnderDiscussion | undefined,
  utteranceType: 'question' | 'directive' | 'response' | 'topic_shift',
  newScope: string | undefined,
  newAxis: string | undefined,
  currentTurn: number,
): QuestionUnderDiscussion | undefined {
  switch (utteranceType) {
    case 'question':
      // New question establishes new QUD
      return {
        question: `What about ${newScope ?? 'the current focus'}?`,
        aboutScope: newScope,
        aboutAxis: newAxis,
        establishedAtTurn: currentTurn,
        active: true,
      };

    case 'directive':
      // Directive may update or maintain QUD
      if (newScope !== undefined && newScope !== currentQUD?.aboutScope) {
        // Scope shift → new QUD
        return {
          question: `Working on ${newScope}`,
          aboutScope: newScope,
          aboutAxis: newAxis ?? currentQUD?.aboutAxis,
          establishedAtTurn: currentTurn,
          active: true,
        };
      }
      // Same scope → maintain QUD
      return currentQUD;

    case 'response':
      // Response continues QUD (but may close it after apply)
      return currentQUD;

    case 'topic_shift':
      // Explicit topic shift replaces QUD
      return {
        question: `Now working on ${newScope ?? 'something new'}`,
        aboutScope: newScope,
        aboutAxis: newAxis,
        establishedAtTurn: currentTurn,
        active: true,
      };

    default:
      return currentQUD;
  }
}


// =============================================================================
// Implicature Detection
// =============================================================================

/**
 * Detect implicatures in an utterance.
 *
 * This is a rule-based detector that identifies common implicature
 * patterns. It does NOT try to infer arbitrary pragmatic meaning —
 * only the documented patterns from the defaults table.
 */
export function detectImplicatures(utterance: string): readonly Implicature[] {
  const lower = utterance.toLowerCase();
  const results: Implicature[] = [];

  // Scalar implicature: "a bit" → not a lot
  if (/\b(a bit|slightly|a touch|a tad|just a little)\b/.test(lower)) {
    results.push({
      type: 'scalar',
      trigger: lower.match(/\b(a bit|slightly|a touch|a tad|just a little)\b/)?.[0] ?? 'a bit',
      conveyance: {
        kind: 'degree_bound',
        bound: {
          boundType: 'upper',
          value: 'small',
          description: 'Scalar implicature: small degree, not large',
        },
      },
      cancellable: true,
      confidence: 'high',
      overrideHint: 'Say "a lot" or "significantly" for larger changes',
    });
  }

  // Exclusivity implicature: "just/only" → nothing else
  if (/\b(just|only)\b/.test(lower)) {
    results.push({
      type: 'exclusivity',
      trigger: lower.match(/\b(just|only)\b/)?.[0] ?? 'just',
      conveyance: {
        kind: 'scope_restriction',
        restriction: 'Only the explicitly named targets should change',
      },
      cancellable: true,
      confidence: 'high',
      overrideHint: 'Remove "just"/"only" or say "and also" to expand scope',
    });
  }

  // Sufficiency implicature: "enough" → stop
  if (/\b(enough|that's enough|sufficient|good enough)\b/.test(lower)) {
    results.push({
      type: 'sufficiency',
      trigger: 'enough',
      conveyance: {
        kind: 'preference',
        preference: {
          axis: 'change_amount',
          direction: 'maintain',
          weight: 'strong',
          description: 'The current state is sufficient — no more changes needed on this axis',
        },
      },
      cancellable: true,
      confidence: 'medium',
      overrideHint: 'Say "actually, a bit more" to continue',
    });
  }

  // Insufficiency implicature: "still too" → need more
  if (/\b(still too|not enough|still not)\b/.test(lower)) {
    results.push({
      type: 'insufficiency',
      trigger: lower.match(/\b(still too|not enough|still not)\b/)?.[0] ?? 'still too',
      conveyance: {
        kind: 'preference',
        preference: {
          axis: 'prior_change',
          direction: 'increase',
          weight: 'strong',
          description: 'Prior change was insufficient — apply more of the same',
        },
      },
      cancellable: true,
      confidence: 'high',
      overrideHint: 'Specify the exact amount or try a different approach',
    });
  }

  // Manner implicature: "carefully" → with constraints
  if (/\b(carefully|gently|subtly|delicately)\b/.test(lower)) {
    results.push({
      type: 'manner',
      trigger: lower.match(/\b(carefully|gently|subtly|delicately)\b/)?.[0] ?? 'carefully',
      conveyance: {
        kind: 'degree_bound',
        bound: {
          boundType: 'upper',
          value: 'small',
          description: 'Manner adverb implies small, conservative changes',
        },
      },
      cancellable: true,
      confidence: 'medium',
      overrideHint: 'Remove the adverb or specify a larger amount',
    });
  }

  return results;
}


// =============================================================================
// Implicature Model Rules (Declarative)
// =============================================================================

/**
 * Normative rules for implicature handling.
 */
export const IMPLICATURE_RULES = {
  /**
   * Rule I1: Defaults are inspectable.
   * Every default interpretation is documented in the canon and
   * visible to the user in the preview.
   */
  I1_DEFAULTS_INSPECTABLE:
    'Every applied default is shown in the preview with its rationale.',

  /**
   * Rule I2: Defaults are overridable.
   * The user can cancel any implicature by being more explicit.
   */
  I2_DEFAULTS_OVERRIDABLE:
    'Every default can be overridden by the user with explicit specification.',

  /**
   * Rule I3: Scalar implicatures bound degree.
   * "A bit" means "not a lot". This provides an upper bound on
   * the degree of change.
   */
  I3_SCALAR_BOUNDS_DEGREE:
    'Scalar modifiers ("a bit", "slightly") set an upper bound on change amount.',

  /**
   * Rule I4: "Just/only" generates exclusivity.
   * Focus particles create a preserve-everything-else constraint.
   */
  I4_EXCLUSIVITY_FROM_FOCUS:
    '"Just"/"only" generate preservation constraints for non-targeted entities.',

  /**
   * Rule I5: QUD inherits scope.
   * Underspecified utterances inherit scope from the active QUD.
   * If no QUD is active, scope resolution follows the standard
   * fallback hierarchy (selection > focus > global).
   */
  I5_QUD_INHERITS_SCOPE:
    'Underspecified scope inherits from the active Question Under Discussion.',

  /**
   * Rule I6: Multiple defaults stack with explicit priority.
   * When multiple defaults apply, constraints are merged.
   * Conflicts between defaults trigger clarification.
   */
  I6_DEFAULTS_STACK:
    'Multiple applicable defaults are merged. Conflicting defaults trigger clarification.',

  /**
   * Rule I7: Implicatures are weaker than explicit statements.
   * If the user explicitly says something that contradicts an
   * implicature, the explicit statement wins.
   */
  I7_EXPLICIT_OVERRIDES_IMPLICIT:
    'Explicit user statements always override conversational implicatures.',
} as const;


// =============================================================================
// Lookup functions
// =============================================================================

/**
 * Find default interpretations matching a phrase.
 */
export function findDefaultInterpretations(phrase: string): readonly DefaultInterpretation[] {
  const lower = phrase.toLowerCase().trim();
  return DEFAULT_INTERPRETATIONS.filter(di =>
    di.phrase === lower || di.variants.some(v => lower.includes(v)),
  );
}

/**
 * Get a default interpretation by ID.
 */
export function getDefaultInterpretation(id: string): DefaultInterpretation | undefined {
  return DEFAULT_INTERPRETATIONS.find(di => di.id === id);
}

/**
 * Total count of default interpretations.
 */
export function defaultInterpretationCount(): number {
  return DEFAULT_INTERPRETATIONS.length;
}
